export const apiErrorCodes = [
  "UNAUTHENTICATED",
  "FORBIDDEN_WORKSPACE",
  "VALIDATION_FAILED",
  "STALE_VERSION",
  "DUPLICATE_MUTATION",
  "DUPLICATE_DOCUMENT",
  "AI_UNAVAILABLE",
  "RATE_LIMITED",
  "UNSUPPORTED_DOCUMENT",
  "PRIVATE_WORKSPACE_EXISTS",
  "CATEGORY_NAME_EXISTS",
  "INSUFFICIENT_BALANCE",
  "SUPER_ADMIN_REQUIRED",
  "EMAIL_ALREADY_REGISTERED",
  "ACTIVE_INVITATION_EXISTS",
  "INVITATION_INVALID",
  "INVITATION_EXPIRED",
  "INVITATION_REDEEMED",
  "INVITATION_BUSY",
  "PASSWORD_POLICY_FAILED",
  "INVITATION_CREATE_FAILED",
  "USER_NOT_FOUND",
  "USER_PROTECTED",
  "USER_EMAIL_MISMATCH",
  "USER_CONFIRMATION_MISMATCH",
  "USER_DELETION_PENDING",
  "USER_SHARED_DATA_CONFLICT",
  "USER_ADMIN_RATE_LIMITED",
  "USER_ADMIN_ACTION_FAILED",
  "INTERNAL_ERROR"
] as const;

export type ApiErrorCode = (typeof apiErrorCodes)[number];

export type ApiErrorResponse = {
  error: {
    code: ApiErrorCode;
    message: string;
    requestId: string;
  };
};
